//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beatrix_Formulario {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Idioma {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Idioma() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Beatrix_Formulario.Idioma", typeof(Idioma).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        internal static string buttonInicioForm1Tareas {
            get {
                return ResourceManager.GetString("buttonInicioForm1Tareas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyectos.
        /// </summary>
        internal static string buttonProyetos1Tareas {
            get {
                return ResourceManager.GetString("buttonProyetos1Tareas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reuniones.
        /// </summary>
        internal static string buttonReuniones1Tareas {
            get {
                return ResourceManager.GetString("buttonReuniones1Tareas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tareas.
        /// </summary>
        internal static string buttonTareas1Tareas {
            get {
                return ResourceManager.GetString("buttonTareas1Tareas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        internal static string labelConfiguracion {
            get {
                return ResourceManager.GetString("labelConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a + Crear reunión.
        /// </summary>
        internal static string labelCrearReunion {
            get {
                return ResourceManager.GetString("labelCrearReunion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desmarcar como completada.
        /// </summary>
        internal static string labelDesmarcar {
            get {
                return ResourceManager.GetString("labelDesmarcar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información.
        /// </summary>
        internal static string labelInformacion1 {
            get {
                return ResourceManager.GetString("labelInformacion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información.
        /// </summary>
        internal static string labelInformacion2 {
            get {
                return ResourceManager.GetString("labelInformacion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información.
        /// </summary>
        internal static string labelInformacion3 {
            get {
                return ResourceManager.GetString("labelInformacion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marcar como completada.
        /// </summary>
        internal static string labelMarcarCompletada {
            get {
                return ResourceManager.GetString("labelMarcarCompletada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Participantes.
        /// </summary>
        internal static string labelParticipantes1 {
            get {
                return ResourceManager.GetString("labelParticipantes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Participantes.
        /// </summary>
        internal static string labelParticipantes2 {
            get {
                return ResourceManager.GetString("labelParticipantes2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Participantes.
        /// </summary>
        internal static string labelParticipantes3 {
            get {
                return ResourceManager.GetString("labelParticipantes3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todas las reuniones.
        /// </summary>
        internal static string labelReuniones {
            get {
                return ResourceManager.GetString("labelReuniones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reuniones proximas.
        /// </summary>
        internal static string labelReunionesProximas {
            get {
                return ResourceManager.GetString("labelReunionesProximas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reuniones.
        /// </summary>
        internal static string labelReunionesTitulo {
            get {
                return ResourceManager.GetString("labelReunionesTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reunión 1.
        /// </summary>
        internal static string labelReunionPanel1 {
            get {
                return ResourceManager.GetString("labelReunionPanel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reunión 2.
        /// </summary>
        internal static string labelReunionPanel2 {
            get {
                return ResourceManager.GetString("labelReunionPanel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reunión 3.
        /// </summary>
        internal static string labelReunionPanel3 {
            get {
                return ResourceManager.GetString("labelReunionPanel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver todas las reuniones.
        /// </summary>
        internal static string labelVerTodasLasReuniones {
            get {
                return ResourceManager.GetString("labelVerTodasLasReuniones", resourceCulture);
            }
        }
    }
}
