//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beatrix_Formulario.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Beatrix_Formulario.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        internal static string Configuracion {
            get {
                return ResourceManager.GetString("Configuracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a + Crear reunión.
        /// </summary>
        internal static string CrearReunion {
            get {
                return ResourceManager.GetString("CrearReunion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desmarcar como completado.
        /// </summary>
        internal static string Desmarcar {
            get {
                return ResourceManager.GetString("Desmarcar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información.
        /// </summary>
        internal static string Informacion1 {
            get {
                return ResourceManager.GetString("Informacion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información.
        /// </summary>
        internal static string Informacion2 {
            get {
                return ResourceManager.GetString("Informacion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información.
        /// </summary>
        internal static string Informacion3 {
            get {
                return ResourceManager.GetString("Informacion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        internal static string InicioForm1Tareas {
            get {
                return ResourceManager.GetString("InicioForm1Tareas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marcar como completado.
        /// </summary>
        internal static string MarcarCompletada {
            get {
                return ResourceManager.GetString("MarcarCompletada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Participantes.
        /// </summary>
        internal static string Participantes1 {
            get {
                return ResourceManager.GetString("Participantes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Participantes.
        /// </summary>
        internal static string Participantes2 {
            get {
                return ResourceManager.GetString("Participantes2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Participantes.
        /// </summary>
        internal static string Participantes3 {
            get {
                return ResourceManager.GetString("Participantes3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyectos.
        /// </summary>
        internal static string Proyetos1Tareas {
            get {
                return ResourceManager.GetString("Proyetos1Tareas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todas las reuniones.
        /// </summary>
        internal static string Reuniones {
            get {
                return ResourceManager.GetString("Reuniones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reuniones.
        /// </summary>
        internal static string Reuniones1Tareas {
            get {
                return ResourceManager.GetString("Reuniones1Tareas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proximas reuniones.
        /// </summary>
        internal static string ReunionesProximas {
            get {
                return ResourceManager.GetString("ReunionesProximas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reuniones.
        /// </summary>
        internal static string ReunionesTitulo {
            get {
                return ResourceManager.GetString("ReunionesTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reunión 1.
        /// </summary>
        internal static string ReunionPanel1 {
            get {
                return ResourceManager.GetString("ReunionPanel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reunión 2.
        /// </summary>
        internal static string ReunionPanel2 {
            get {
                return ResourceManager.GetString("ReunionPanel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reunión 3.
        /// </summary>
        internal static string ReunionPanel3 {
            get {
                return ResourceManager.GetString("ReunionPanel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tareas.
        /// </summary>
        internal static string Tareas1Tareas {
            get {
                return ResourceManager.GetString("Tareas1Tareas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver todas las reuniones.
        /// </summary>
        internal static string VerTodasLasReuniones {
            get {
                return ResourceManager.GetString("VerTodasLasReuniones", resourceCulture);
            }
        }
    }
}
